application: ssmbus
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- appstats: on

handlers:
- url: /css
  static_dir: css
- url: /js
  static_dir: js
- url: /.*
  script: router.APP

libraries:
- name: webapp2
  version: "latest"
- name: jinja2
  version: "latest"
